server:
  port: 8083

spring:
  application:
    name: ressource-service
  datasource:
    url: jdbc:mysql://localhost:3306/resource_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/